require('basic')
require('plugins-config/plugins')
-- require('plugins-config/compe-config')
require('plugins-config/cmp-config')
require('plugins-config/lsp-config')
require('plugins-config/nvim-tree-config')
require('plugins-config/bufferline-config')
require('plugins-config/gitsigns-config')
